name: cifar10
print_freq: 100
workers: 4
log_dir: 'logs'
model_dir: 'ckps'
output_dir: 'output/cifar10'
iter: 'cifar10_IF100'
GPUS: [0]

imb_factor: 0.01
imb_type: 'exp'
quantity_ratio: 1.0

loss: 'CrossEntropy'
s: 30
max_m: 0.1
gamma: 1.5

scheduler: 'ppw'
drw: 160
ppw_min: 100
ppw_max: 160
ppw_alpha: 5
weighted_sampler: 'default'

mixup: 'ppmix'
ppmix_epoch_min: 100
ppmix_epoch_max: 160
ppm_alpha: 3

# dataset & model setting
dataset: 'cifar10'
data_path: '...'
num_classes: 10

backbone: 'resnet32_fe'
resume: '../ckps/model_best.pth.tar'
head_class_idx:
  - 0
  - 3
med_class_idx:
  - 3
  - 7
tail_class_idx:
  - 7
  - 10


# Train
lr: 0.1
batch_size: 128
weight_decay: 2e-4
num_epochs: 20
momentum: 0.9
cos: False

alpha: 1.0




