name: cifar100
print_freq: 100
workers: 4
log_dir: 'logs'
model_dir: 'ckps'
output_dir: 'output/cifar10/0.2_10'
iter: 'cifar10_IF100'
GPUS: [7]

imb_factor: 0.01
imb_type: 'exp'
imb_ratio: 1.0

loss: 'CRILoss'
s: 10
max_m: 0.2
gamma: 1.5

scheduler: 'ppw'
drw: 160
ppw_min: 100
ppw_max: 160
ppw_alpha: 5

mixup: 'ppmix'
ppmix_epoch_min: 100
ppmix_epoch_max: 160
ppm_alpha: 3

# dataset & model setting
dataset: 'cifar100_CRI'
data_path: '/home/xmj/4T/work/FOLDAM/main/datasets/imbalance_cifar100'
num_classes: 100

backbone: 'resnet32_fe'
resume: ''
head_class_idx:
  - 0
  - 36
med_class_idx:
  - 36
  - 71
tail_class_idx:
  - 71
  - 100

# distributed training
deterministic: False
distributed: False
gpu: null
world_size: -1
rank: -1
dist_url: 'tcp://224.66.41.62:23456'
dist_backend: 'nccl'
multiprocessing_distributed: False

# Train
lr: 0.1
batch_size: 128
weight_decay: 2e-4
num_epochs: 200
momentum: 0.9
cos: False

alpha: 1.0




