name: cifar10
print_freq: 100
workers: 4
log_dir: 'logs'
model_dir: 'ckps'
output_dir: 'output/cifar10/0.2_10'
iter: 'cifar10_IF100'
GPUS: [7]

imb_factor: 0.01
imb_type: 'exp'
imb_ratio: 1.0

loss: 'CRILoss'
s: 30
max_m: 0.1
gamma: 1.0

scheduler: 'ppw'
drw: 160
ppw_min: 100
ppw_max: 160
ppw_alpha: 5

mixup: 'ppmix'
ppmix_epoch_min: 100
ppmix_epoch_max: 160
ppm_alpha: 3

# dataset & model setting
dataset: 'cifar10_CRI'
data_path: '/home/xmj/4T/work/FOLDAM/main/datasets/imbalance_cifar10'
num_classes: 10

backbone: 'resnet32_fe'
resume: ''
head_class_idx:
  - 0
  - 3
med_class_idx:
  - 3
  - 7
tail_class_idx:
  - 7
  - 10

# Train

lr: 0.1
batch_size: 128
weight_decay: 2e-4
num_epochs: 200
momentum: 0.9
cos: False

alpha: 1.0




